accounts/urls.py
from django.urls import path 

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
    
]



config/urls.py
from django.contrib import admin
from django.urls import path, include


admin.site.site_header = 'TDO-APP'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
    path('accounts/', include('accounts.urls')),
]

todoapp/urls.py
from django.urls import path 

from . import views


app_name = 'todoapp'

urlpatterns = [
    path('', views.home_, name='todo_home'),
    path('list/', views.todo_list_view, name='todo_list'),
    path('create/', views.todo_item_create, name='create_todo_item'),
    path('delete/<int:pk>/', views.todo_item_delete, name='delete_todo_item'),
]


accounts/models.py
from django.db import models

# Create your models here.

todoapp/models.py
from django.db import models
from django.contrib.auth.models import User 


class TodoItem(models.Model):
    work = models.CharField(max_length=100)
    checked = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(blank=True, null=True, )
    
    
    def check_item(self):
        self.checked = True
    
    def __str__(self):
        return f'{self.work}'

todoapp/forms.py
from django import forms

from . import models 


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = models.TodoItem
        fields = ['work', 'date']




accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout



def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
        
    form = UserCreationForm()
            
    return render(request, 'accounts/signup.html', {'form': form})



def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/')
        
    form = AuthenticationForm()
        
    return render(request, 'accounts/login.html', {'form': form})
    

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('/')


todoapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from . import models
from . import forms

def home_(request):
    return render(request, 'todoapp/home.html')


@login_required(login_url='/accounts/login')
def todo_list_view(request):
    user = request.user 
    todo_queryset = models.TodoItem.objects.filter(owner = user)
    
    if request.method == 'POST':
        checked_list = request.POST.getlist('checked')
        checked_list = [int(i) for i in checked_list]
        for todoitem in todo_queryset:
            if todoitem.id in checked_list:
                models.TodoItem.objects.filter(id = todoitem.id).update(checked=True)
            else:
                models.TodoItem.objects.filter(id = todoitem.id).update(checked=False)

        return redirect('/list')
    
    todo_item_len = len(todo_queryset)

    return render(request, 'todoapp/todo_list.html', {'todo_list':todo_queryset, 'todo_list_len':todo_item_len})



@login_required(login_url='/accounts/login')
def todo_item_create(request):
    user = request.user
    if request.method == 'POST':
        form = forms.TodoItemForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = user
            instance.save()
            return redirect('todoapp:todo_list') 
        
    form = forms.TodoItemForm()
    
    return render(request, 'todoapp/create_todo_item.html', {'form':form})


def todo_item_delete(request,pk):
    try:
        todo_item = models.TodoItem.objects.get(pk=pk)
    except:
        return redirect('todoapp:toso_list')
    
    if todo_item.owner == request.user:
        todo_item.delete()
        return redirect('/list')
    else:
        return redirect('todoapp:toso_list')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}login{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">login</button>
</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}sign up{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">sign up</button>
</form>

{% endblock %}

templates/_base.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'todoapp/styles.css' %}">
    
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'todoapp:todo_home' %}">Todo App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'todoapp:todo_list' %}">Todo list</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">contact us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">account</a>
              </li>
                <li class="nav-item">
                  {% if user.is_authenticated %}
                  <form action='{% url "accounts:logout" %}' method="POST">
                    {% csrf_token %}
                    <button class='btn btn-link nav-link'>logout</button>
                  </form>
                  {% else %}
                  <a class='btn btn-link' href="{% url 'accounts:login' %}">login</a> / <a class='btn btn-link' href="{% url 'accounts:signup' %}">signup</a>
                  {% endif %}
                </li>
              </div>
            </ul>
          </div>
          
      </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

todoapp/templates/todoapp/create_todo_item.html

{% extends '_base.html' %}
{% block pagetitle %} create todo item {% endblock %}
{% block content %}
<div class="container create-form-container">
    <h1>create</h1>
<form class="create-todo-form" action="" method="POST">
    <div class='input-container'>
        <label for="">{{form.work.label}}</label>
        <input class="form-control" type="text" name="work" id="id_work">
        <p class='helper-text'>please write your todo job</p>
    </div>
    <div class='input-container'>
        <label for="">{{form.date.label}}</label>
        <input class="form-control" type="datetime-local" name="date" id="id_date">
        <p class='helper-text'>here you can pick a date and time for your job. not required!</p>
    </div>
    <button class='btn btn-primary' type="submit">add</button>
    {% csrf_token %}
</form>
</div>
{% endblock %}

todoapp/templates/todoapp/home.html
{% extends '_base.html' %} 
{% block pagetitle %} Todo App {% endblock %} 
{% block content %}
<h1>Home Template</h1>
{% endblock %}

todoapp/templates/todoapp/todo_list.html
{% extends '_base.html' %}

{% block pagetitle %} todos list {% endblock %}

{% block content %}

<div class='list-container'>
{% if todo_list_len == 0 %}
<div>
  <h3>nothing here ...</h3>
  <a class='link' href="{% url 'todoapp:todo_item_create' %}">you can add a job to do from here</a>
</div>
{% else %}
<div class="todo-list-container">
  <form method="POST" action="{% url 'todoapp:todo_list' %}" id='todo-list-form'>
    <div class="todo-list">
      <ul class="list-group">
        {% for todoitem in todolist %}
        <li class="list-group-item todo-item">
          <div class="todo-item-content">
                  {% if todoitem.checked %}
                  <input class="check-input form-check-input job-done-input"  type="checkbox" name='checked' checked value="{{todoitem.id}}" aria-label="...">
                  <div class="job-done-text job-text">
                    <h6>{{todoitem.work}}</h6>
                    <p>{{todoitem.date}}</p>
                  </div>
                  {% else %}
                  <input class="check-input form-check-input " type="checkbox"  name='checked' value="{{todoitem.id}}" aria-label="...">
                  <div class="job-undone-text job-text">
                    <h6>{{todoitem.work}}</h6>
                    <p>{{todoitem.date}}</p>
                  </div>
                  {% endif %}
                </div>
                <div class="todo-item-action">
                  <a class='btn btn-danger' href="{% url 'todoapp:todo_item_delete' todoitem.id %}"><i class="bi bi-trash-fill"></i></a>
                  <a class='btn btn-secondary' href="{% url 'todoapp:todo_item_delete' todoitem.id %}"><i class="bi bi-pencil"></i></a>
                </div>
            </li>
            {% endfor %}
            <a class='btn btn-light' href="/create"><i class="bi bi-plus"></i> add new work</a>
      </ul>
    </div>
        {% csrf_token %}
        <button class='btn btn-primary' id='print-paper'><i class="bi bi-printer"></i></button>
  </form>
</div>
{% endif %}

</div>

<script>
  let check_input = document.getElementsByName('checked');
  let form = document.getElementById('todo-list-form')
  let print_btn = document.getElementById('print-paper')
  console.log(check_input);
  check_input.forEach(element => {
    element.addEventListener('click', function(){
      form.submit()
    })
  });
  print_btn.addEventListener('click',function(){
    print()
  })

</script>

{% endblock %}